# Generated by Django 4.2.11 on 2024-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='tg',
            field=models.CharField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley', max_length=200),
        ),
    ]
