# Generated by Django 4.2.11 on 2024-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_github_user_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.CharField(default='пока ничего нет', max_length=200),
        ),
    ]
